---
include:
  - template: Workflows/Branch-Pipelines.gitlab-ci.yml

stages:
  - build

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - ash ci-build/kaniko.sh

# vim: ai ts=2 sw=2 et sts=2 ft=yaml
